# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SoC_MIOEMIO.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# XDC: c:/devWorks/SoC_MIO_EMIO/SoCMIOEMIO/SoCMIOEMIO.gen/sources_1/bd/design_1/design_1_ooc.xdc
