set_property IOSTANDARD LVCMOS33 [get_ports {GPIO2_Outputs_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO2_Outputs_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Inputs_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Inputs_tri_i[0]}]
set_property PACKAGE_PIN R14 [get_ports {GPIO2_Outputs_tri_o[1]}]
set_property PACKAGE_PIN P14 [get_ports {GPIO2_Outputs_tri_o[0]}]
set_property PACKAGE_PIN D19 [get_ports {GPIO_Inputs_tri_i[1]}]
set_property PACKAGE_PIN D20 [get_ports {GPIO_Inputs_tri_i[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN N16 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN M14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN L20 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN L19 [get_ports {GPIO_0_0_tri_io[3]}]
