# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
# IP: The module: 'design_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
# IP: The module: 'design_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/20002890/SoC_7_Timers_GIC/SoC_7_Timers_GIC.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
