
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2019.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*

* 
* Description: Profiling Configuration parameters. These parameters
* can be overwritten through run configuration in SDK
*
*******************************************************************/

#ifndef _PROFILE_CONFIG_H
#define _PROFILE_CONFIG_H

#define BINSIZE 4
#define CPU_FREQ_HZ 666666687
#define SAMPLE_FREQ_HZ 100000
#define TIMER_CLK_TICKS 6666
#define PROC_CORTEXA9 1
#define ENABLE_SCU_TIMER 1
#define ENABLE_SYS_INTR 1
#define PROFILE_TIMER_BASEADDR 0xF8F00600
#define PROFILE_TIMER_INTR_ID 29
#define SCUGIC_CPU_BASEADDR 0xF8F00100
#define SCUGIC_DIST_BASEADDR 0xF8F01000

#endif

/******************************************************************/

