set_property SRC_FILE_INFO {cfile:C:/Users/20002890/SoC_Multiple_IRQ_F2P/SoC_Multiple_IRQ_F2P.srcs/constrs_1/new/SoC_Multiple_IRQ_F2P.xdc rfile:../../../SoC_Multiple_IRQ_F2P.srcs/constrs_1/new/SoC_Multiple_IRQ_F2P.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P13 [get_ports {gpio_rtl_0_tri_i[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports {gpio_rtl_tri_i[0]}]
