set_property SRC_FILE_INFO {cfile:C:/Users/20002890/WS2812/WS2812.srcs/constrs_1/new/ws2812.xdc rfile:../../../WS2812.srcs/constrs_1/new/ws2812.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R11 [get_ports d_out]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M11 [get_ports FCLK_CLK1]
