# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/74HC595Matrix.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vhdlnoclk_0_0/design_1_vhdlnoclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vhdlnoclk_0_0 || ORIG_REF_NAME==design_1_vhdlnoclk_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_VHDL_74HC595_Matrix_0_2/design_1_VHDL_74HC595_Matrix_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_VHDL_74HC595_Matrix_0_2 || ORIG_REF_NAME==design_1_VHDL_74HC595_Matrix_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
