set_property SRC_FILE_INFO {cfile:C:/devWorks/RGB/RGBVivado/RGBVivado.srcs/constrs_1/new/RGBROM.xdc rfile:../../../RGBVivado.srcs/constrs_1/new/RGBROM.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports d_out_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports clk_in1_0]
