# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
# IP: The module: 'design_1_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
# IP: The module: 'design_1_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/VHDL_VIO/VHDL_VIO.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
