set_property SRC_FILE_INFO {cfile:C:/Users/20002890/SoC_6_GPIO/SoC_6_GPIO.srcs/constrs_1/new/SoC_6_GPIO.xdc rfile:../../../SoC_6_GPIO.srcs/constrs_1/new/SoC_6_GPIO.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {GPIO2_Outputs_tri_o[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports {GPIO2_Outputs_tri_o[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {GPIO_Inputs_tri_i[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D20 [get_ports {GPIO_Inputs_tri_i[0]}]
